### ISSUE TITLE
Add specs for multiple db adapters

### ISSUE THREAD

**Issue by abinoam** [ErvalhouS/quantum_fields#6]
**quantum_fields** should have specs for postgresql and mysql.

I think we should follow Travis instructions as it would be possible to run specs both locally and at travis.

https://docs.travis-ci.com/user/database-setup/

I think I can work on this at this weekend.
But opening an issue so if I don't progress until monday we could at least discuss and and see if anyone can do it.

**Comment by ErvalhouS** [comment]
#7 does configure multiple database testing, should we discuss this further? Is there a need to implement other adapters or the ones we have until now are enough?

**Comment by abinoam** [comment]
We can close this for now. 👍
